version: 1.0.{build}
image: Visual Studio 2017
nuget:
  account_feed: true
  disable_publish_on_pr: true 
build_script:

- cmd: >-
    nuget restore

    msbuild /t:build;pack
artifacts:
- path: '**\*.nupkg'