name: build

env:
  BuildParameters: "-c Release /p:RepositoryUrl=https://github.com/${{ github.repository }}"
  RepositoryUrl: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

on:
  push:
    tags: [ '*' ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/')
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      shell: bash

    - name: Pack
      run: dotnet pack ${{ env.BuildParameters }} /p:BuildVersion=${{ steps.get_version.outputs.VERSION }} -o artifacts

    - name: Upload nuget packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget
        path: 'artifacts/*.nupkg'

    - name: Publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push artifacts\*.nupkg --source ${{ env.RepositoryUrl }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate --no-symbols true
